# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

t_cpp <- function(mat) {
    .Call('_GFusionMed_t_cpp', PACKAGE = 'GFusionMed', mat)
}

prod_cpp <- function(mat1, mat2) {
    .Call('_GFusionMed_prod_cpp', PACKAGE = 'GFusionMed', mat1, mat2)
}

t_prod_cpp <- function(mat1, mat2) {
    .Call('_GFusionMed_t_prod_cpp', PACKAGE = 'GFusionMed', mat1, mat2)
}

prod_t_cpp <- function(mat1, mat2) {
    .Call('_GFusionMed_prod_t_cpp', PACKAGE = 'GFusionMed', mat1, mat2)
}

inverse_cpp <- function(mat) {
    .Call('_GFusionMed_inverse_cpp', PACKAGE = 'GFusionMed', mat)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_GFusionMed_dmvnrm_arma', PACKAGE = 'GFusionMed', x, mean, sigma, logd)
}

rmvnrm_arma <- function(n, mu, sigma) {
    .Call('_GFusionMed_rmvnrm_arma', PACKAGE = 'GFusionMed', n, mu, sigma)
}

